In [7]:
# 1-1
# Scikit-learn 網站中
# (https://scikit-learn.org/stable/datasets/toy_dataset.html)
# 有提供一些Toy datasets
# 其中，有個dataset為boston (波士頓房屋價格)。首先，請匯入boston 資料集。

from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
import seaborn as sns
%matplotlib inline
font = FontProperties(fname='C:\Windows\Fonts\mingliu.ttc')

boston_data = datasets.load_boston() 
# 回傳格式為dictionary
# Key 值分別為 "data"、"target"、"target_names"、"DESCR"
boston_data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': 'C:\\Users\\USER\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'}

In [8]:
#1-2
#秀出此資料集中共有幾個features，分別顯示feature_names。
boston_data['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [9]:
# 1-2
len(boston_data['feature_names'])

13

In [10]:
# 1-3
# 請用DataFrame方式將boston的data讀入X變數，並設定column的名稱為feature_names。
# 接著同樣用DataFrame方式將boston的target讀入Y變數，並設定column的名稱為「MEDV」。
# 最後利用concat函數將X與Y合併在同一個DataFrame中，
x = pd.DataFrame(boston_data['data'], columns=boston_data['feature_names'])
y = pd.DataFrame(boston_data['target'], columns=['MEDV'])
# 語法 : pd.contact( [x,y], axis = 1)
boston_data = pd.concat([x,y], axis=1) # 欄位合併
boston_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [11]:
# 1-3 並秀出前五筆資料。
boston_data.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [12]:
# 1-4
# 請確認此資料集中是否有空缺值
# (亦即計算上一題的DataFrame中每個欄位的空缺值數目)。
boston_data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [13]:
# 1-5
# 透過相關係數，可輔助迴歸模型之建立，
# 請秀出13個特徵變數(X變數)和Y變數(MEDV)的相關係數；
# 其中，相關係數請顯示至小數點第二位。

## 線性回歸，進行散步圖(相關係數)分析
## round(2) 小數點2位
boston_data1 = boston_data.corr()["MEDV"].round(2) 
boston_data1

CRIM      -0.39
ZN         0.36
INDUS     -0.48
CHAS       0.18
NOX       -0.43
RM         0.70
AGE       -0.38
DIS        0.25
RAD       -0.38
TAX       -0.47
PTRATIO   -0.51
B          0.33
LSTAT     -0.74
MEDV       1.00
Name: MEDV, dtype: float64

In [14]:
# 1-6
# 篩選自變數的基本方法可挑選相關係數較高的變數，
# 由上一題的結果中，請挑出X變數中與Y變數相關係數大於0.65的變數(不論正相關或負相關)，
# 將其設定為新的X變數，Y變數仍為MEDV。
# 接著使用sklearn中的函式把X、Y變數分為training及test datasets。
# 其中，training的資料占80 %、test 20%，並設定Random_state = 10，
# 並秀出 X_train的前五筆資料。

from sklearn.model_selection import train_test_split

x1 = boston_data[['LSTAT']]
x2 = boston_data[['RM']]
X = pd.concat([x1,x2], axis=1)
y = boston_data[['MEDV']]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=10) 

X_train.head(5)

     LSTAT     RM
50   13.45  5.963
367  13.33  3.863
34   20.34  6.096
78   12.34  6.232
172  14.69  5.572

In [15]:
# 1-7
# 承上題，請使用sklearn中的線性迴歸模式套件，
# 以training datasets的資料建立線性迴歸模型，
# 並分別秀出截距項、X變數之係數及R2

from sklearn import linear_model
#plt.style.use('ggplot')

regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

r_squared = regr.score(X_train, y_train)

print('截距項 = ', regr.intercept_)
print('X係數 = ', regr.coef_)
print('R平方 = ',r_squared)

截距項 =  [3.14487154]
X係數 =  [[-0.68480439  4.43045078]]
R平方 =  0.6363353379616083

In [16]:
# 1-8
# 衡量迴歸方程式好壞，常用的指標為均方根誤差(RMSE)，其公式如下：
# 請用test datasets計算均方根誤差(RMSE)，請顯示至小數點第四位，並秀出結果。
rmse = np.sqrt(((regr.predict(X_test) - y_test) ** 2). mean ( )).round(4)
print(len(rmse))
print(type(rmse))
print("均方根誤差 (root-mean-square error, RMSE) = " , rmse )

1
<class 'pandas.core.series.Series'>
均方根誤差 (root-mean-square error, RMSE) =  MEDV    6.4344
dtype: float64

In [17]:
# 1-9
# 衡量迴歸方程式好壞，另一個常用指標為平均絕對誤差(MAE)，其公式如下：
# 請用test datasets計算平均絕對誤差(MAE)，請顯示至小數點第四位，並秀出結果。
mae = (abs(regr.predict(X_test) - y_test).mean()).round(4)
print("平均絕對誤差(MAE) = ", mae)

平均絕對誤差(MAE) =  MEDV    4.5826
dtype: float64

In [28]:
# 1-10
# 請使用第六題找出的X變數與Y變數(MEDV)，在分割為測試集與訓練集的情況下，
# 其中測試集佔i/100(i=1~99)，並設定Random_state = 10，
# 請找出測試集的均方根誤差RMSE值最小時的i，及其RMSE(請顯示至小數點第四位)
# (Note: 程式請使用迴圈，不要手動一次一次跑)
from sklearn import linear_model
from sklearn.model_selection import train_test_split


x1 = boston_data[['LSTAT']]
x2 = boston_data[['RM']]
X = pd.concat([x1,x2], axis=1)
y = boston_data[['MEDV']]
# X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=10) 
regr = linear_model.LinearRegression()

min_rmse = 5
rmse = 0
i_index = 0
for i in range(99): # i = 0 ~ 98
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = (i+1)/100, random_state=10) 
    regr.fit(X_train, y_train)
    
    rmse = np.sqrt(((regr.predict(X_test) - y_test) ** 2). mean ( )).round(4)
    rmse = float(rmse)
    # print(type(rmse))
    # print(min_rmse)
    if rmse < min_rmse:
        min_rmse = rmse
        i_index = i + 1
print("i = ", i_index)
print("min_rmse = ", min_rmse)

i =  1
min_rmse =  3.7476

In [27]:
# 1-11
# 同樣請使用第六題找出的X變數與Y變數(MEDV)，在分割為測試集與訓練集的情況下，
# 其中測試集佔i/100(i=1~99)，並設定Random_state = 10，
# 請找出測試集的R2最大時的i，及其R2 (請顯示至小數點第四位)
# (Note: 程式請使用迴圈，不要手動一次一次跑)
from sklearn import linear_model
from sklearn.model_selection import train_test_split


x1 = boston_data[['LSTAT']]
x2 = boston_data[['RM']]
X = pd.concat([x1,x2], axis=1)
y = boston_data[['MEDV']]

regr = linear_model.LinearRegression()

r_squared_max = 0
i_index = 0
for i in range(99): # i = 0 ~ 98
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = (i+1)/100, random_state=10) 
    regr.fit(X_train, y_train)
    
    r_squared = regr.score(X_train, y_train)
    
    if r_squared > r_squared_max:
        r_squared_max = r_squared
        i_index = i + 1
        

print("i = ", i_index)
print("r_squared_max = ", r_squared_max.round(4))

i =  97
r_squared_max =  0.7069

In [36]:
# 1-12
# 若將13個特徵變數同時放入X變數，而Y變數為MEDV，
# 接著使用sklearn中的函式把X、Y變數分為training及test datasets；
# 其中，training的資料占80 %、test 20%，並設定Random_state = 10，
# 再使用sklearn中的線性迴歸模式套件，以training datasets的資料建立線性迴歸模型，
# 並分別秀出截距項、X變數之係數及R2。

from sklearn import linear_model # 回歸模式套件
from sklearn.model_selection import train_test_split

X = boston_data.iloc[:,0:13]
y = boston_data[['MEDV']]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=10) 

# 設定 linear regression 物件
regr_12 = linear_model.LinearRegression()

# 以 training datasets 的資料建立線性迴歸模型
regr_12.fit(X_train, y_train)

# 計算 R2
r_squared = regr_12.score(X_train, y_train)

print("截距 = ", regr_12.intercept_)
print("X變數之係數 = ", regr_12.coef_)
print("R平方 = ", r_squared)

截距 =  [36.53305138]
X變數之係數 =  [[-1.28180656e-01  6.31981786e-02 -7.57627602e-03  1.97451452e+00
  -1.62719890e+01  3.10845625e+00  1.62922153e-02 -1.48301360e+00
   3.03988206e-01 -1.20820710e-02 -8.20305699e-01  1.14189890e-02
  -5.81626431e-01]]
R平方 =  0.750121534530608

In [37]:
# 1-13
# 承上題，
# 假如13個特徵變數的值分別為0.00632、18、2.31、0、0.538、6.575、
# 65.2、4.09、1、296、15.3、396.9、4.98
# 請依據(12)題所建出的迴歸模型，預測房屋的中位數價格(MEDV)

x_variable = np.array([0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98]).reshape((1, -1))
medv_predict = regr_12.predict(x_variable)

print("medv_predict = ", medv_predict)

medv_predict =  [[30.14551898]]